#!/bin/bash
#
# Name: cpall
# This script copies a very long listing of files

# Copyright (c) MBARI 2007
# Author: D. Cline
# Date: Octoboer 25, 2007
#
#exit on error; this will exit this bash script when any command exists with
#a non-zero exit code
set -e 
###################################################################################
# Print usage
print_usage()
{
  echo "  "
  echo "  "
  echo -e "\033[1mUSAGE:  cpall [filepattern] [directoryname] \033[0m"
  echo "  "
  echo "  Copy all files in current directory with the pattern f0*.ppm to directory ppmframes"
  echo "      (Example:  cpall "f0*.ppm" ppmframes"
  echo "  "
}
###################################################################################
if test $# -lt 2
then print_usage
exit 1
fi
filepattern=$1
directory=$2
tmp=./tmp.$RANDOM
if [ -d $directory ]; then
    echo "Copying files with stem $filepattern to directory $directory"
    echo "find ./ -maxdepth 1 -type f -name '$filepattern' -exec cp {} $directory \;" > $tmp
    chmod u+x $tmp
    $tmp
    rm $tmp
else
    echo -e "\033[1mcpall:  ERROR - $2 is not a valid directory\033[0m"
    exit 1
fi

