#!/bin/bash
#set -x
#
# Name: ppm2jpg
# This script converts a .PPM image file to a .JPG file format.
#
# Usage:  ppm2jpg filename.ppm
#
# Copyright (c) MBARI 2002
# Author: Karen A. Salamy
# Date: August 5, 2002
# Revised: October 22, 2002
#
# List usage properties should the user only type the script name.
if test $# -ne 1
then
  echo "  "
  echo -e "\033[1mUSAGE: ppm2jpg filename[.PPM]\033[0m"
  echo "  "
  exit 1
fi

# Declare variable filename.
filename=$1

# Convert the file name to a *.PPM file based on its extension.
# If the file is already a *.JPG - state so. If the file is not a 
# *.JPG file format, remind the user that they have made an ERROR.
for filename in "$@"; do
  jpgfile=${filename%.*}.jpg

  case $filename in
        *.jpg ) echo "  "
                echo "procfile:  ERROR - $filename is already a .jpg file!"
                echo "  "
                exit 0 ;;

        *.ppm ) pnmtojpeg $filename > $jpgfile ;;

            * ) echo "  "
                echo "procfile:  ERROR - $filename is not a .ppm file!"
                echo "  "
                exit 1 ;;

  esac

done
