#!/bin/bash
#set -x
#
# Name: ppm2mov 
# This script creates a Quicktime move from ppms
# 
# Usage: ppm2mov <ppmdirectory> <moviename> 
#
# Copyright (c) MBARI 2003
# Author: Danelle Cline, Karen Salamy 
# Date: July 18, 2003 
#
#exit on error; this will exit this bash script when any command exists with
#a non-zero exit code
set -e 
###################################################################################
# Print usage
print_usage()
{
  echo "  "
  echo "  "
  echo -e "\033[1mUSAGE:  ppm2mov -i [ppmdirectory] -f [frameseed] -o [filename.mov] [OPTION] \033[0m"
  echo "  "
  echo -e "\033[1mexample:  ppm2mov -i ./ppms -f T -o results.mov \033[0m"  
  echo "  " 
  echo "OPTION"
  echo "  " 
  echo -e "\033[1m -s \033[0m"
  echo "     ppm input directory is defined relative to local machine users scratch directory"
  echo "      (Example:  ppm2mov -s -i testclip/20040513T001230 -o 20040513T001230.mov)"
  echo "  " 
  echo "  "
  exit 1
}

###################################################################################
input=0
output=0
fileseed=0
cero=0
use_system_scratch=0

# Check arguments
while getopts i:o:f:s option 
do
  case $option in   
   s)  use_system_scratch=1;;
   i)  input="$OPTARG";;
   o)  output="$OPTARG";;
   f)  fileseed="$OPTARG";;
   *)  echo "Unimplemented option chosen."
       echo "  "
       print_usage;;
  esac
done

if [ $input = 0 -o $output = 0 -o $fileseed = 0  ];then 
print_usage
exit 1
fi

# Add the path to the aved binaries if AVED_BIN is set
if [ $AVED_BIN ]; then
    PATH=$PATH:$AVED_BIN
    export PATH
fi

# Format the output directory
if [ $use_system_scratch = 1 ]; then
    if [ $SCRATCH_DIR ]; then
	input=$SCRATCH_DIR/$USER/$input
    else
	echo "Error - \$SCRATCH_DIR environment variable is not defined"
	exit 1
    fi
fi

# check if directory is valid 
if [ -d $input ] ; then
    echo "Found $input ppm directory"
    cd $input
else
    echo -e "\033[1mprocfile:  ERROR - $input is not a valid directory\033[0m"
    exit 1;
fi 

# Verify the file is a .mov file
case $output in 
   *.mov ) echo "Creating Quicktime movie called $output";; 
   *.MOV ) echo "Creating Quicktime movie called $output";; 
       * ) echo -e "\033[1mprocfile:  ERROR - $output is not an .mov file!\033[0m"
           echo "  "
           exit 1 ;;
esac

abspath=`cd $input && pwd`  

# List how many frames created and state the start and end frame information.`
startframe=`find $fileseed*.ppm | head --lines=1 | sed "s/\($fileseed$cero\)\([0-9]*\)\(.ppm\)/\2/"`
endframe=`find $fileseed*.ppm | tail --lines=1 | sed "s/\($fileseed$cero\)\([0-9]*\)\(.ppm\)/\2/"` 
echo $startframe
echo $endframe
exit

# Make a Quicktime movie (.mov) out of the ppm RGB frames
# NOTE - THIS WILL MAKE A VERY LARGE FILE - THIS USES UNCOMPRESSED FRAMES
echo "mq -i $input -s $fileseed$startframe -e $fileseed$endframe -o $output -q 200 -f 29.97 -v"

exit 0
