#!/bin/bash
#set -x
#
# Name: dpx2mov 
# This script creates a Quicktime move from dpx files
# 
# Usage: dpx2mov <ppmdirectory> <moviename> 
#
# Copyright (c) MBARI 2005
# Author: Danelle Cline, Karen Salamy 
# Date: November 1, 2005
#
# List usage properties should the user not list 3 arguments
if test $# -lt 3 
then
  echo "  "
  echo "  "
  echo -e "\033[1mUSAGE:  dpx2mov [dpxdirectory] [frameseed] [filename.mov]\033[0m"
  echo "  "
  echo -e "\033[1mexample:  dpx2mov ./ dive257 dive256.mov \033[0m"
  echo "  "
  exit 1
fi

# check if directory called ppm is valid 
if [ -d $1 ] ; then
    echo "Found dpx directory"
    cd $1 
else
    echo -e "\033[1mprocfile:  ERROR - $1 is not a valid directory\033[0m"
    exit 1;
fi 

# Verify the frame seed is correct
# ls $2*.ppm will not work with long ppms listings - ls fails!!
ls | grep $2[^dpx] | head --lines=1 > /dev/null 2>&1

if [ $? -eq 0 ] ; then
    echo "Found dpx files"
else
    echo -e "\033[1mprocfile:  ERROR - cannot find dpx files with ls | grep $2[^dpx] | head --lines=1 \033[0m"
    exit 1
fi

# Verify the file is a .mov file
case $3 in 
   *.mov ) echo "Creating Quicktime movie called $3";; 
   *.MOV ) echo "Creating Quicktime movie called $3";; 
       * ) echo -e "\033[1mprocfile:  ERROR - $3 is not an .mov file!\033[0m"
           echo "  "
           exit 1 ;;
esac


# List how many frames created and get start/end frame of dpx files
startframe=`ls $1 | grep $2 | grep dpx | head --lines=1 | sed "s/\($2\.\)\([0-9]*\)\(.dpx\)/\2/"` 
endframe=`ls $1 | grep $2 | grep dpx | tail --lines=1 | sed "s/\($2\.\)\([0-9]*\)\(.dpx\)/\2/"` 

# Convert to ppms
echo "Converting dpx to ppm"
size=`gm identify $2.$startframe.dpx | cut -f3 -d " " | cut -f1 -d "+"`
ls $1 | grep $2 | grep dpx | sed "s/^/dpx2ppm /" > tmp
chmod u+x tmp
./tmp

# Make a Quicktime movie (.mov) out of the ppm RGB frames
mq -i $2 -s $startframe -e $endframe -o $3 -q 200 -f 29.97 -v

# Remove ppms
echo "Removing temporary ppms"
ls $1 | grep $2 | grep ppm | sed "s/^/rm /" > tmp
chmod u+x tmp
./tmp
rm tmp

# Move out of the movie directory.
echo "Done"
