#!/bin/bash
#set -x
#
# Name: ppm2jpeg
# This script converts a *.PPM image file to a *.JPEG file format.
#
# Usage:  ppm2jpeg filename.ppm
#
# Copyright (c) MBARI 2002
# Author: Karen A. Salamy
# Date: August 5, 2002
# Revised: October 22, 2002
#
#exit on error; this will exit this bash script when any command exists with
#a non-zero exit code
set -e 
# List usage properties should the user only type the script name.
if test $# -ne 1
then
  echo "  "
  echo -e "\033[1mUSAGE: ppm2jpeg filename[.PPM]\033[0m"
  echo "  "
  exit 1
fi

# Declare variable filename.
filename=$1

# Convert the file name to a *.PPM file based on its extension.
# If the file is already a *.JPEG - state so. If the file is not a 
# *.JPEG file format, remind the user that they have made an ERROR.
for filename in "$@"; do
  jpegfile=${filename%.*}.jpeg

  case $filename in
        *.jpeg ) echo "  "
                echo "procfile:  ERROR - $filename is already a .jpeg file!"
                echo "  "
                exit 0 ;;

        *.ppm ) pnmtojpeg $filename > $jpegfile ;;

            * ) echo "  "
                echo "procfile:  ERROR - $filename is not a .ppm file!"
                echo "  "
                exit 1 ;;

  esac

done
