#!/bin/bash
#set -x
#
# Name: renameall 
# This script renames a long file listing

# Copyright (c) MBARI 2007
# Author: D. Cline
# Date: January 08, 2007
#
#exit on error; this will exit this bash script when any command exists with
#a non-zero exit code
set -e 
# Get the environment for Condor jobs
. /etc/profile
###################################################################################
# Print usage
print_usage()
{
  echo "  "
  echo "  "
  echo -e "\033[1mUSAGE:  renameall [oldfilestem] [newfilestem] \033[0m"
  echo "  "
  echo "  Rename all files in this directory starting with f0 to T0 "
  echo "      (Example:  renameall f0 f000"
  echo "  "
}
###################################################################################
if test $# -lt 2
then print_usage
exit 1
fi
oldfilestem=$1
newfilestem=$2
tmp=/tmp/removeall.$RANDOM

echo "Getting list of files in $PWD..."
find ./ -type f | grep $oldfilestem > $tmp

#if file is not zero size, then go through each entry and rename
if [ -s $tmp ]; then
for name in `cat $tmp` 
do
    frame=`echo $name | sed "s/\(\.\/$oldfilestem\.\)\([0-9]*\)\(.dpx\)/\2/"`
    if [ -f $frame ]; then
	echo "File already exists" 
    else
	if [ "$name" != "$newfilestem.$frame.dpx" ]; then
    		echo "Moving $name to $newfilestem.$frame.dpx..."
    		mv -f $name $newfilestem.$frame.dpx
	fi
    fi
done
else
   echo -e "\033[1mrenameall: ERROR - No files to rename with the filestem $oldfilestem\033[0m"
   exit 1
fi

