#!/bin/bash
#set -x
#
# Name: rmall
# This script removes a long listing of files

# Copyright (c) MBARI 2005
# Author: D. Cline
# Date: February 07, 2005
#
#
#exit on error; this will exit this bash scrip when
#any command exists with a non-zero exit code
set -e
###################################################################################
# Print usage
print_usage()
{
  echo "  "
  echo "  "
  echo -e "\033[1mUSAGE:  rmall [filepattern*]\033[0m"
  echo "  "
  echo "  Remove all files in directory starting with f0"
  echo "      (Example:  rmall 'f0*'"
  echo "  "
  echo "  Note that the filepattern must be in ' ' " 
}
###################################################################################
if test $# -lt 1 
then print_usage
exit 1
fi
filepattern=$1
tmp=./tmp.$RANDOM
echo "Removing files with stem $filepattern"
echo "find ./ -type f -name '$filepattern' -exec rm {} \;" > $tmp
chmod u+x $tmp
$tmp 
rm -f $tmp
