<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist SYSTEM "file://localhost/System/Library/DTDs/PropertyList.dtd">
<plist version="0.9">
  <dict>
    <key>IFPkgFlagDefaultLocation</key>
    <string>/Applications/${bundleName}</string>
    <key>CFBundleIdentifier</key>
    <string>org.mbari.aved.ui.AVEDac.pkg</string>
    <key>LSEnvironment</key>
            <dict>
                <key>DYLD_LIBRARY_PATH</key>
                <string>/Applications/AVEDac:/Applications/MATLAB/MATLAB_Compiler_Runtime/v710/runtime/maci:/Applications/MATLAB/MATLAB_Compiler_Runtime/v710/sys/os/maci:/Applications/MATLAB/MATLAB_Compiler_Runtime/v710/bin/maci:/System/Library/Frameworks/JavaVM.framework/JavaVM:/System/Library/Frameworks/JavaVM.framework/Libraries:/lib:/usr/lib:/Applications/AVEDac0.4.3</string>
                <key>XAPPLRESDIR</key>
                <string>/Applications/MATLAB/MATLAB_Compiler_Runtime/v710/X11/app-defaults</string>
            </dict>   
  </dict>
</plist>