#!/bin/bash
#This script assumes you have installed mbarivision to /usr/local/aved/bin
#If it is installed somewhere else, then change this script accordingly
#or change your aved.sh/aved.csh.
 
USERID=`id -u`
if [ $USERID != 0 ]; then
	echo "You must be root user to run install"
	exit 0
fi

mkdir -p /usr/local/aved/scripts
mkdir -p /usr/local/aved/bin
cp -fp * /usr/local/aved/scripts

# If a profile.d directory exists, install paths there 
if [ -d /etc/profile.d ]; then 
cat >/etc/profile.d/aved.sh <<_ACEOF 
export AVED_BIN=/usr/local/aved/bin
export PATH=$PATH:/usr/local/aved/scripts:$AVED_BIN 
_ACEOF

cat >/etc/profile.d/aved.csh <<_ACEOF
setenv AVED_BIN=/usr/local/aved/bin
setenv PATH=$PATH:/usr/local/aved/scripts:$AVED_BIN
_ACEOF
fi

# If a profile file exists, install paths there
if [ -e /etc/profile ]; then
cat >>/etc/profile <<_ACEOF
export AVED_BIN=/usr/local/aved/bin
export PATH=$PATH:/usr/local/aved/scripts:$AVED_BIN
_ACEOF
fi

