#!/bin/bash
#
# set -x
# Name: installbeo
# This script configures the beowulf for AVED parallel processing
# Copyright (c) MBARI 2007
# Author: D. Cline
# Date: July 10, 2007
#
#
#######################################################################################
# Defines the pmbarivision file with machine names and port ranges for MPI execution
# Check if root
USERID=`id -u`
if [ $USERID != 0 ]; then
	echo "You must be root to run install"
	exit 0
fi

# Initialize port numbers
pvisworker_portstart=9900
pvisworker_portend=10000

pmbarivis_portstart=9700
pmbarivis_portend=9800

# Create the mpi config file
file=/etc/aved/pmbarivision.mpi
cat >$file <<_ACEOF
#######################################################################
# Configuration file for AVED parallel version
#######################################################################
# Defines the ports to use for the parallel mbarivision
# The PMBARIVISION_PORT_START/END must be a different
# range than the PVISIONWORKER_PORT_START/END
#######################################################################
PMBARIVISION_PORT_START=$pmbarivis_portstart
PMBARIVISION_PORT_END=$pmbarivis_portend

#######################################################################
# Defines the ports to use for the pvision workers
#######################################################################
PVISIONWORKER_PORT_START=$pvisworker_portstart
PVISIONWORKER_PORT_END=$pvisworker_portend
_ACEOF

# Create if needed and move into the installation directory
if [ ! -d /etc/aved ]; then
    mkdir /etc/aved
fi
pushd /etc/aved;

# Move out of the installation directory
popd;

# Calculate port range overlap. I'm sure there is a more elegant way to do this, but this works fine
overlap=`seq $pvisworker_portstart $pvisworker_portend | grep "9800\|9760"`

# Test for correct port ranges and if there is an overlap in ports
if [ $pvisworker_portstart -ge $pvisworker_portend ]; then
    echo "Invalid range for PVISIONWORKER_PORT_START $pmbarivis_portstart and PVISIONWORKER_PORT_END $pmbarivis_portend"
    exit 1
fi

if [ $pmbarivis_portstart -ge $pmbarivis_portend ]; then
    echo "Invalid range for PVISIONWORKER_PORT_START $pmbarivis_portstart and PVISIONWORKER_PORT_END $pmbarivis_portend"
    exit 1
fi

if [ "$overlap" != "" ]; then 
    echo "Error PMBARIVISION_PORT_START/END ranges must not overlap with PVISIONWORKER_PORT_START/END"
    echo "Port ranges overlap at: "
    echo "$overlap"
    exit 1
fi

# Copy the configuration to all the cluster nodes
cpush /etc/aved/  

# Copy the mpich configuration to the machines files
# Set this to the correct directory of your MPICH2 installation
cpush /opt/mpich2-1.0/etc/mpd.hosts 

exit 0
