#!/bin/bash
#
# Name: install
#
# *Important* run this in the same directory as the scripts
#
# USAGE:  install
#
# This script installs the AVEDac user enviroment on
# a single host. To setup the  environment on a Beowulf
# cluster, run the installbeo script instead.
#
# This scripts installs scripts to /usr/local/aved/bin
# Change this script accordingly, if installation needed
# in another location, e.g. /home/shared/aved
#
# Copyright (c) MBARI 2010
# Author: D. Cline
#
# exit on error - this will exit this bash script when
# any command exits with a non-zero exit code
set -e
 
USERID=`id -u`
if [ $USERID != 0 ]; then
	echo "You must be root user to run install"
	exit 0
fi

install_dir=/usr/local/aved

echo "Creating $install_dir/scripts"
mkdir -p $install_dir/scripts

echo "Copying scripts to $install_dir"
cp -Rfp * $install_dir/scripts

# Install paths in profile.d directory if it exists
if [ -d /etc/profile.d ]; then

# Make backup 
if [ -e /etc/profile.d/aved.sh ]; then
  dt=`date '+%m%d%y_%H:%M:%S' --reference=/etc/profile.d/aved.sh`
  cp /etc/profile.d/aved.sh /etc/profile.d/aved.sh.$dt
fi
   
echo "Creating /etc/profile.d/aved.sh" 
cat >/etc/profile.d/aved.sh <<_ACEOF 
export AVED_BIN=$install_dir/bin
_ACEOF

if [ $MPDIR ]; then
cat >>/etc/profile.d/aved.sh <<_ACEOF 
export MPDIR=$MPDIR 
export PATH=$PATH:$install_dir/scripts:$AVED_BIN:$MPDIR/bin 
_ACEOF
else
cat >>/etc/profile.d/aved.sh <<_ACEOF 
export PATH=$PATH:$install_dir/scripts:$AVED_BIN
_ACEOF
fi

if [ $SCRATCH_DIR ]; then
cat >>/etc/profile.d/aved.sh <<_ACEOF 
export SCRATCH_DIR=$SCRATCH_DIR
_ACEOF
fi

# Make backup 
if [ -e /etc/profile.d/aved.csh ]; then
  dt=`date '+%m%d%y_%H:%M:%S' --reference=/etc/profile.d/aved.csh`
  cp /etc/profile.d/aved.csh /etc/profile.d/aved.csh.$dt
fi

echo "Creating /etc/profile.d/aved.csh" 
cat >/etc/profile.d/aved.csh <<_ACEOF
setenv AVED_BIN "$install_dir/bin"
_ACEOF

if [ $MPDIR ]; then
cat >>/etc/profile.d/aved.csh <<_ACEOF
setenv MPDIR "${MPDIR}" 
setenv PATH "${PATH}:$install_dir/scripts:$AVED_BIN:$MPDIR/bin"
_ACEOF
else
cat >>/etc/profile.d/aved.csh <<_ACEOF
setenv PATH "${PATH}:$install_dir/scripts:$AVED_BIN"
_ACEOF
fi

if [ $SCRATCH_DIR ]; then
cat >>/etc/profile.d/aved.csh <<_ACEOF
set SCRATCH_DIR = $SCRATCH_DIR
_ACEOF
fi

fi

