#!/bin/bash
#
# Name: installbeo
#
# This script configures the beowulf for parallel processing with
# pmbarivision and pvisionTCPmbari.
# 
# Password-less ssh login is also required for running these binaries
# with the MPI libraries
#
# Copyright (c) MBARI 2010
# Author: D. Cline
#
# exit on error - this will exit this bash script when any command exits with
# a non-zero exit code
set -e

# Check if root
USERID=`id -u`
if [ $USERID != 0 ]; then
	echo "You must be root to run install"
	exit 0
fi

# Initialize port numbers
pvisworker_portstart=9900
pvisworker_portend=10000

pmbarivis_portstart=9700
pmbarivis_portend=9800

# Create the mpi config file
file=/etc/aved/pmbarivision.mpi
cat >$file <<_ACEOF
#######################################################################
# Configuration file for AVED parallel version
#######################################################################
# Defines the ports to use for the pmbarivision
# The PMBARIVISION_PORT_START/END must be a different
# range than the PVISIONWORKER_PORT_START/END
#######################################################################
PMBARIVISION_PORT_START=$pmbarivis_portstart
PMBARIVISION_PORT_END=$pmbarivis_portend

#######################################################################
# Defines the ports to use for the pvisionTCPmbari workers
#######################################################################
PVISIONWORKER_PORT_START=$pvisworker_portstart
PVISIONWORKER_PORT_END=$pvisworker_portend
_ACEOF

# Create install directory and move into it
mkdir -p /etc/aved
pushd /etc/aved;

# Move out of the installation directory
popd;

# Test for correct port definitions
if [ $pvisworker_portstart -ge $pvisworker_portend ]; then
    echo "Invalid range for PVISIONWORKER_PORT_START $pmbarivis_portstart and PVISIONWORKER_PORT_END $pmbarivis_portend"
    exit 1
fi

if [ $pmbarivis_portstart -ge $pmbarivis_portend ]; then
    echo "Invalid range for PVISIONWORKER_PORT_START $pmbarivis_portstart and PVISIONWORKER_PORT_END $pmbarivis_portend"
    exit 1
fi

# Calculate port range overlap between vision workers and pmbarivision
# I'm sure there is a more elegant way to do this, but this works fine
overlap=`seq $pvisworker_portstart $pvisworker_portend | grep "9800\|9760"`

if [ "$overlap" != "" ]; then 
    echo "Error PMBARIVISION_PORT_START/END ranges must not overlap with PVISIONWORKER_PORT_START/END"
    echo "Port ranges overlap at: "
    echo "$overlap"
    exit 1
fi

# Copy the configuration to all the cluster nodes
cpush /etc/aved/  

exit 0
