#!/bin/bash
#set -x
#
# Name: postscript_checkfile
# This script checks if processing was completed by checking if the
# xml file exists and is non-empty
#
# This and returns 0 if ok, otherwise 1
#
# This is inteded to be run as a post-script in the AVED Condor DAG 
#
# Copyright (c) MBARI 2007
# Author: D. Cline
# Date: July 2007, 2007
###################################################################################
# Print usage
print_usage()
{
  echo "  "
  echo "  "
  echo -e "\033[1mUSAGE:  postscript_checkfile [results.xml] \033[0m"
  echo "  "
  echo "  Check if the file 20040513T001230.events.xml exists and is non-empty"
  echo "  "  
  echo "  " 
}
###################################################################################
if test $# -ne 1 
then print_usage
exit 1
fi

if test ! -e "$1" || test -z "`cat $1`" 
then
    echo "File is bad"
    exit 1
else
    echo "File is good"
    exit 0
fi

